name: Build on push

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build with Gradle
        run: |
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          echo 'android.native.buildOutput=verbose' >> gradle.properties
          ./gradlew assembleFossDebug \
          -Pandroid.injected.signing.store.file="${{ github.workspace }}/debug.keystore" \
          -Pandroid.injected.signing.store.password="android" \
          -Pandroid.injected.signing.key.alias="androiddebugkey" \
          -Pandroid.injected.signing.key.password="android"
      - name: Upload built apk
        if: success()
        uses: actions/upload-artifact@v4
        with:
          path: |
            ${{ github.workspace }}/app/build/outputs/apk/foss/debug/*.apk
